apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::590183905007:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-BvHVCKjZnEVe
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::590183905007:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-04-02T19:37:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1308"
  uid: 73dc495b-304a-436b-af74-66396a5e4018
